DevOps_iConfigurator/Models/CSV_model.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DevOps_iConfigurator.Models
{
    public class CSV_model
    {
        public string Instance_Type { get; set; }
        public string OS_System { get; set; }
        public string Tenancy { get; set; }
        public string Price_per_Unit { get; set; }
        public string Unit { get; set; }
        public string Termtype { get; set; }
    }
}

DevOps_iConfigurator/Controllers/DotNetImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DevOps_iConfigurator.Controllers
{
    public class DotNetImageController : Controller
    {
        // GET: DotNetImage
        public ActionResult Index()
        {
            return View();
        }
    }
}

DevOps_iConfigurator/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DevOps_iConfigurator.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Details_DevOps()
        {
            ViewBag.Message = "Your Details page.";

            return View();
        }
    }
}

DevOps_iConfigurator/Controllers/JavaImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DevOps_iConfigurator.Controllers
{
    public class JavaImageController : Controller
    {
        // GET: JavaImage
        public ActionResult Index()
        {
            return View();
        }
    }
}

DevOps_iConfigurator/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text;

namespace DevOps_iConfigurator.Controllers
{
    public class QuestionsController : Controller
    {
        public static StringBuilder sb = new StringBuilder();
        private DevOpsCGEntities db = new DevOpsCGEntities();

       
        [HttpGet]
        public ActionResult Index(int? id, int? selid)
         {
            if (id is null)
            {
                Session["Option"] = "";
                return View(db.SearchQuestion1(1).ToList());
            }
            else

            if (id > 11)
            {
                Session["Option"] += selid.ToString() + ",";
                return RedirectToAction("Summary");
            }
            else
            {
                
                Session["Option"] += selid.ToString() + ",";
                return View(db.SearchQuestion1(id).ToList());
            }
          
        }

        public ActionResult Summary()
        {
           
            ViewBag.Message = "Select the plan...";
            return View();
        }

        public ActionResult UserDashBoard()
        {

            ViewBag.Message = "Installation part goes here...";
            return View();
        }


    }
}

DevOps_iConfigurator/Controllers/ToolsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DevOps_iConfigurator.Controllers
{
    public class ToolsController : Controller
    {
        // GET: Tools
        public ActionResult Index()
        {
            System.Diagnostics.Process.Start(@"D:\\Users\\sjamgade\\Desktop\\DevOps_iConfigurator\\DevOps_iConfigurator\\CF_Batch_Script\\Jenkins.bat");
            System.Diagnostics.Process.Start(@"D:\\Users\\sjamgade\\Desktop\\DevOps_iConfigurator\\DevOps_iConfigurator\\CF_Batch_Script\\Tomcat.bat");
            System.Diagnostics.Process.Start(@"D:\\Users\\sjamgade\\Desktop\\DevOps_iConfigurator\\DevOps_iConfigurator\\CF_Batch_Script\\artifactory.bat");
            System.Diagnostics.Process.Start(@"D:\\Users\\sjamgade\\Desktop\\DevOps_iConfigurator\\DevOps_iConfigurator\\CF_Batch_Script\\sonar.bat");

            return View();
            
            
           
        }
    }
}

DevOps_iConfigurator/Views/DotNetImage/Index.cshtml
@{
    ViewBag.Title = "Java Home Page";
}


<script type="text/javascript">
    function JSFunction() {



        location.href = '@Url.Action("Index", "Questions")';

    }
</script>

<!DOCTYPE HTML>
<html>


<head>
    <title>@ViewBag.Title  - My ASP.NET Application</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <!--5grid-->
    <script src="css/5grid/viewport.js"></script><!--[if lt IE 9]><script src="css/5grid/ie.js"></script><![endif]-->
    <link rel="stylesheet" href="css/5grid/core.css" />
    <link rel="stylesheet" href="css/style.css" />
    <!--[if IE 9]><link rel="stylesheet" href="css/style-ie9.css" /><![endif]-->
</head>

<body>
    <!-- ********************************************************* -->
    <header id="header_outer">
        <div class="container">
            <div class="header_section">
                <div class="logo">
                    <a href="javascript:void(0)"><img class="img1" src="~/img/CGLogo.png" alt=""></a>
                </div>
                <nav class="nav" id="nav1">
                    <ul class="">
                        <li><a href="@Url.Action("Index","Home")" class="contact_btn">Home</a></li>
                    </ul>

                </nav>

            </div>
        </div>
    </header>
    <div id="banner-wrapper">
        <div class="5grid">
            <div class="12u-first">

                <div id="banner">

                </div>

            </div>
        </div>
    </div>
    <div class="row">

        <center><img class="img" src="~/img/DotNetImage.jpg" height="500" width="800" /></center>
        <br />
        <center><h1><input type="button" class="contact_btn" onclick="JSFunction()" value="Next"></h1></center>
    </div>
</body>
</html>

DevOps_iConfigurator/Views/Home/Details_DevOps.cshtml
@{
    ViewBag.Title = "Details_DevOps";
}
<!DOCTYPE HTML>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, maximum-scale=1">
    <title>Homepage</title>
    <link rel="icon" href="favicon.png" type="image/png">
    <link href="css/bootstrap.css" rel="stylesheet" type="text/css">
    @*<link href="css/style.css" rel="stylesheet" type="text/css">*@
    <link href="css/linecons.css" rel="stylesheet" type="text/css">
    <link href="css/font-awesome.css" rel="stylesheet" type="text/css">
    <link href="css/responsive.css" rel="stylesheet" type="text/css">
    <link href="css/animate.css" rel="stylesheet" type="text/css">
    <link href="~/css/style.css" rel="stylesheet" />
    <link href='https://fonts.googleapis.com/css?family=Lato:400,900,700,700italic,400italic,300italic,300,100italic,100,900italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Dosis:400,500,700,800,600,300,200' rel='stylesheet' type='text/css'> 
</head>

<body>
    <header id="header_outer">
        <div class="container">
            <div class="header_section">

                <nav class="nav" id="nav1">
                    <ul class="">
                        <li><a href="@Url.Action("Index","Home")" class="contact_btn">Home</a></li>
                    </ul>

                </nav>

            </div>
        </div>
    </header>
    <br />

    <h2>Details of portal goes here....</h2>
</body>
</html>

DevOps_iConfigurator/Views/Home/Index.cshtml
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, maximum-scale=1">
    <title>Homepage</title>
    <link rel="icon" href="favicon.png" type="image/png">
    <link href="css/bootstrap.css" rel="stylesheet" type="text/css">
    <link href="css/style.css" rel="stylesheet" type="text/css">
    <link href="css/linecons.css" rel="stylesheet" type="text/css">
    <link href="css/font-awesome.css" rel="stylesheet" type="text/css">
    <link href="css/responsive.css" rel="stylesheet" type="text/css">
    <link href="css/animate.css" rel="stylesheet" type="text/css">

    <link href='https://fonts.googleapis.com/css?family=Lato:400,900,700,700italic,400italic,300italic,300,100italic,100,900italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Dosis:400,500,700,800,600,300,200' rel='stylesheet' type='text/css'>

    <!-- =======================================================
    Theme Name: Butterfly
    Theme URL: https://bootstrapmade.com/butterfly-free-bootstrap-theme/
    Author: BootstrapMade
    Author URL: https://bootstrapmade.com
    ======================================================= -->

    <script type="text/javascript" src="js/jquery.1.8.3.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.js"></script>
    <script type="text/javascript" src="js/jquery-scrolltofixed.js"></script>
    <script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="js/jquery.isotope.js"></script>
    <script type="text/javascript" src="js/wow.js"></script>
    <script type="text/javascript" src="js/classie.js"></script>

    <script type="text/javascript">
        $(document).ready(function (e) {
            $('.res-nav_click').click(function () {
                $('ul.toggle').slideToggle(600)
            });

            $(document).ready(function () {
                $(window).bind('scroll', function () {
                    if ($(window).scrollTop() > 0) {
                        $('#header_outer').addClass('fixed');
                    } else {
                        $('#header_outer').removeClass('fixed');
                    }
                });
            });
        });
        function resizeText() {
            var preferredWidth = 767;
            var displayWidth = window.innerWidth;
            var percentage = displayWidth / preferredWidth;
            var fontsizetitle = 25;
            var newFontSizeTitle = Math.floor(fontsizetitle * percentage);
            $(".divclass").css("font-size", newFontSizeTitle)
        }
    </script>
</head>
<body>
    <!--Header_section-->
    <header id="header_outer">
        <div class="container">
            <div class="header_section">
                <div class="logo"><a href="javascript:void(0)"><img src="~/img/CGLogo.png" alt=""></a></div>
                <nav class="nav" id="nav">
                    <ul class="toggle">
                        <li><a href="@Url.Action("Index","Home")">Home</a></li>
                        <li><a href="@Url.Action("Index","Home")">About</a></li>
                        <li><a href="@Url.Action("Index","Home")">Contact Us</a></li>
                      
                    </ul>
                    <ul class="">
                        <li><a href="@Url.Action("Index","Home")">Home</a></li>
                        <li><a href="@Url.Action("About","Home")">About</a></li>
                        <li><a href="@Url.Action("Contact","Home")">Contact Us</a></li>
                       
                    </ul>
                </nav>
                <a class="res-nav_click animated wobble wow" href="javascript:void(0)"><i class="fa-bars"></i></a>
            </div>  
        </div>
    </header>
    <!--Header_section-->
    <!--Top_content-->
    <section id="top_content" class="top_cont_outer">
        <div class="top_cont_inner">
            <div class="container">
                <div class="top_content">
                    <div class="row">
                        <div class="col-lg-5 col-sm-7">
                            <div class="top_left_cont flipInY wow animated">
                                @*<h3>Colourful &amp; sexy!</h3>*@
                                <h1>
                                    DevOps iConfigurator
                                </h1>

                               
                                @*<p> Accusantium quam, aliquam ultricies eget tempor id, aliquam eget nibh et. Maecen aliquam, risus at semper. Proin iaculis purus consequat sem cure digni ssim. Donec porttitora entum. </p>*@
                                <a href="@Url.Action("Details_DevOps", "Home")" class="learn_more2">Learn more</a>
                            </div>
                        </div>
                        <div class="col-lg-7 col-sm-5"> </div>
                    </div>
                </div>
            </div>
        </div>

        <h2>Select Language</h2>
        <div class="container">
            <div class="service_area">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="service_block">
                            <div class="service_icon delay-03s animated wow  zoomIn">
                                <a href="@Url.Action("Index","JavaImage")">
                                    <span><i class="fa-flash"></i></span>
                                </a>
                            </div>
                            <h3 class="animated fadeInUp wow">Java</h3>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="service_block">
                            <div class="service_icon icon2  delay-03s animated wow zoomIn">
                                <a href="@Url.Action("Index","DotNetImage")">
                                    <span><i class="fa-comments"></i></span>
                                </a>
                            </div>
                            <h3 class="animated fadeInUp wow">.Net</h3>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="service_block">
                            <div class="service_icon icon3  delay-03s animated wow zoomIn"> <span><i class="fa-shield"></i></span> </div>
                            <h3 class="animated fadeInUp wow">Demo</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
   
    @*<section id="service">
        <div class="container">
    
            <div class="service_area">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="service_block">
                            <div class="service_icon delay-03s animated wow  zoomIn"> 
                                <a href="@Url.Action("Index","JavaImage")">
                                    <span><i class="fa-flash"></i></span>
                                </a>
                            </div>
                            <h3 class="animated fadeInUp wow">Java</h3>                  
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="service_block">
                            <div class="service_icon icon2  delay-03s animated wow zoomIn"> 
                                <a href="@Url.Action("Index","DotNetImage")">
                                    <span><i class="fa-comments"></i></span>
                                    </a>
                            </div>
                            <h3 class="animated fadeInUp wow">.Net</h3>                    
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="service_block">
                            <div class="service_icon icon3  delay-03s animated wow zoomIn"> <span><i class="fa-shield"></i></span> </div>
                            <h3 class="animated fadeInUp wow">Demo</h3>                   
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>*@   
</body>
</html>

DevOps_iConfigurator/Views/JavaImage/Index.cshtml
@{
    ViewBag.Title = "Java Home Page";
}


<script type="text/javascript">
    function JSFunction() {



        location.href = '@Url.Action("Index", "Questions")';

    }
</script>

<!DOCTYPE HTML>
<html>


<head>
    <title>@ViewBag.Title  - My ASP.NET Application</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <!--5grid-->
    <script src="css/5grid/viewport.js"></script><!--[if lt IE 9]><script src="css/5grid/ie.js"></script><![endif]-->
    <link rel="stylesheet" href="css/5grid/core.css" />
    <link rel="stylesheet" href="css/style.css" />
    <!--[if IE 9]><link rel="stylesheet" href="css/style-ie9.css" /><![endif]-->
</head>

<body>
    <!-- ********************************************************* -->
    <header id="header_outer">
        <div class="container">
            <div class="header_section">
                <div class="logo">
                <a href="javascript:void(0)"><img class="img1" src="~/img/CGLogo.png" alt=""></a>
                </div>
                <nav class="nav" id="nav1">
                    <ul class="">
                        <li><a href="@Url.Action("Index","Home")" class="contact_btn">Home</a></li>
                    </ul>

                </nav>
               
         </div>
        </div>
    </header>
    <div id="banner-wrapper">
        <div class="5grid">
            <div class="12u-first">

                <div id="banner">
                   
                </div>

            </div>
        </div>
    </div>
    <div class="row">
       
        <center><img  class="img" src="~/img/JavaImage.jpg" height="500" width="800" /></center>
        <br />
        <center><h1><input type="button" class="contact_btn" onclick="JSFunction()" value="Next"></h1></center>
    </div>
</body>
</html>

DevOps_iConfigurator/Views/Questions/Index.cshtml
@model IEnumerable<DevOps_iConfigurator.SearchQuestion1_Result>

<script type="text/javascript">
    function JSFunction() {

        var valu = 0;
        var selid = 0;
        var radios = document.getElementsByName('Question');

        for (var i = 0, length = radios.length; i < length; i++) {
            if (radios[i].checked) {
                // do whatever you want with the checked radio
                valu = (radios[i].value);
                selid = (radios[i].id);

                // only one radio can be logically checked, don't check the rest
                break;
            }
        }
        if (valu == 0)
        {
            alert("please select the option");
        }
        else
        {
           
            location.href = '@Url.Action("Index", "Questions")?id=' + valu + '&&selid=' + selid;
        }
    }
</script>



<!DOCTYPE HTML>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, maximum-scale=1">
    <title>Homepage</title>
    <link rel="icon" href="favicon.png" type="image/png">
    <link href="css/bootstrap.css" rel="stylesheet" type="text/css">
    @*<link href="css/style.css" rel="stylesheet" type="text/css">*@
    <link href="css/linecons.css" rel="stylesheet" type="text/css">
    <link href="css/font-awesome.css" rel="stylesheet" type="text/css">
    <link href="css/responsive.css" rel="stylesheet" type="text/css">
    <link href="css/animate.css" rel="stylesheet" type="text/css">
    <link href="~/css/style.css" rel="stylesheet" />
    <link href='https://fonts.googleapis.com/css?family=Lato:400,900,700,700italic,400italic,300italic,300,100italic,100,900italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Dosis:400,500,700,800,600,300,200' rel='stylesheet' type='text/css'>
</head>

<body>
    <!-- ********************************************************* -->
    <header id="header_outer">
        <div class="container">
            <div class="header_section">
                <div class="logo"><a href="javascript:void(0)"><img src="~/img/CGLogo.png" alt=""></a></div>
                <nav class="nav" id="nav1">
                    <ul>
                        <li><a href="@Url.Action("Index","Home")" class="contact_btn">Home</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    
    <table align="center" border="1">
        <tr>
            <td colspan="2" align="center">
                <h2>Select your application details</h2>
            </td>
        </tr>
        <tr>
            <td align="center">
                <div class="quote_section">
                    <p>
                        @Html.DisplayFor(modelItem => Model.First().Questions)
                        <br />
                    </p>
                    <div>
                        <table align="center">
                            <tr>
                                <td>
                                    @foreach (var item1 in Model)
                                    {
                                        <font size="3">
                                            <input type="radio" name="Question" id=@Html.DisplayFor(modelItem => item1.OID) value=@Html.DisplayFor(modelItem => item1.NextQID) />
                                            @Html.DisplayFor(modelItem => item1.Options)
                                        </font>
                                    }
                                </td>
                            </tr>
                        </table>
                    </div>
                    @{
                        string Disabled = "block";
                        if (Model.First().Questions.Equals("What SCM tool is required?"))
                        {
                            Disabled = "none";
                        }                        
                    }
                    <div id="filters" class="sixteen columns">
                        <ul class="clearfix">
                            <li>
                                <a class="" href="#" data-filter=".branding" onclick="window.history.go(-1); return false;" style="display:@Disabled;">
                                    <h5>Back</h5>
                                </a>
                            </li>
                            <li>
                                <a class="" href="#" data-filter=".branding" onclick="JSFunction()">
                                    <h5>Next</h5>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </td>
        </tr>
    </table>
</body>
</html>

DevOps_iConfigurator/Views/Questions/Summary.cshtml
@{
    Layout = null;
}
<script type="text/javascript">
    function JSFunction() {
        location.href = '@Url.Action("Index", "Tools")';
    }
      function JSFunction1() {
        location.href = '@Url.Action("UserDashBoard", "Questions")';
    }
</script>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, maximum-scale=1">
    <title>Homepage</title>
    <link rel="icon" href="favicon.png" type="image/png">
    <link href="css/bootstrap.css" rel="stylesheet" type="text/css">  
    <link href="css/linecons.css" rel="stylesheet" type="text/css">
    <link href="css/font-awesome.css" rel="stylesheet" type="text/css">
    <link href="css/responsive.css" rel="stylesheet" type="text/css">
    <link href="css/animate.css" rel="stylesheet" type="text/css">
    <link href="~/css/style.css" rel="stylesheet" />
    <link href='https://fonts.googleapis.com/css?family=Lato:400,900,700,700italic,400italic,300italic,300,100italic,100,900italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Dosis:400,500,700,800,600,300,200' rel='stylesheet' type='text/css'>
    <link href="~/css/main.css" rel="stylesheet" />
</head>
<body>
    <header id="header_outer">
        <div class="container">
            <div class="header_section">
                <div class="logo"><a href="javascript:void(0)"><img src="~/img/CGLogo.png" alt=""></a></div>
                <nav class="nav" id="nav1">
                    <ul>
                        <li><a href="@Url.Action("Index", "Home")" class="contact_btn">Home</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>

    <h2>
        @ViewBag.Message
        <br />
    </h2>
    <table align="center" border="1" style="width:100%">
        <tbody>
            <tr>
                <th>TOOLS</th>
                <th>INSTANCE TYPE</th>
                <th>COST</th>
            </tr>
            @{
                DevOpsCGEntities db = new DevOpsCGEntities();
                DevOps_iConfigurator.Helper.AwsCost hp = new DevOps_iConfigurator.Helper.AwsCost();
                string[] ids = Session["Option"].ToString().Split(',');
                string t2microcost = hp.GetAwsPrice("Linux", "t2.micro");
                string t2mediumcost = hp.GetAwsPrice("Linux", "t2.medium");
                double cost = 0; 

                <tr>

                    <td align="center">
                        @for (int i = 0; i < 3; i++)
                        {
                            cost += Convert.ToDouble(t2microcost.Substring(1, 6));
                            int opid = Convert.ToInt32(ids[i]);
                            string option = db.Questions_Options.First(a => a.OID == opid).Options.ToString();
                            @option
                            if (i < 2)
                            {
                                <text>+</text>
                            }
                        }
                    </td>
                    <td align="center">t2 micro</td>               
                    <td align="center">@t2microcost</td>
                    
                   
                </tr>

                for (int i = 3; i < 4; i++)
                {
                    cost += Convert.ToDouble(t2mediumcost.Substring(1, 6));
                    int opid = Convert.ToInt32(ids[i]);
                    string option = db.Questions_Options.First(a => a.OID == opid).Options.ToString();
                    <tr>
                        <td align="center">@option</td>
                        <td align="center">t2 medium</td>
                        <td align="center">@t2mediumcost</td>
                     
                    </tr>


                }

                for (int i = 7; i < 9; i++)
                {
                    cost += Convert.ToDouble(t2microcost.Substring(1, 6));
                    int opid = Convert.ToInt32(ids[i]);
                    string option = db.Questions_Options.First(a => a.OID == opid).Options.ToString();
                    <tr>
                        <td align="center">@option</td>
                        <td align="center">t2 micro</td>
                        <td align="center">@t2microcost</td>
                     
                    </tr>
                }               
             
}
        </tbody>
    </table>
    <div><h5> Total Cost: $@cost;</h5></div> 
   
            <div id="filters" class="sixteen columns">
                <ul class="clearfix">
                    <li>
                        <a class="" href="#" data-filter=".branding" onclick="JSFunction()">
               
                            <h5>Submit</h5>
                        </a>
                    </li>
                    </ul>
                </div>
    <!-- ********************************************************* -->
    <center><h2>OR</h2></center>
    <!-- ********************************************************* -->

    <table align="center" border="1" style="width:100%">
        <tbody>
            <tr>
                <th>TOOLS</th>
                <th>INSTANCE TYPE</th>
                <th>COST</th>
            </tr>          
@{
    DevOpsCGEntities db1 = new DevOpsCGEntities();
    string[] id = Session["Option"].ToString().Split(',');
    <tr>
        <td align="center">
            @for (int i = 0; i < 3; i++)
            {
                int opid = Convert.ToInt32(ids[i]);
                string option = db.Questions_Options.First(a => a.OID == opid).Options.ToString();
                @option
                if (i < 2)
                {
                    <text>+</text>
                }
            }
        </td>  
        <td rowspan="5" align="center">t2 micro</td>
        <td rowspan="5" align="center">$100</td>
    </tr>
            for (int i = 3; i < 4; i++)
            {
                int opid = Convert.ToInt32(ids[i]);
                string option = db.Questions_Options.First(a => a.OID == opid).Options.ToString();
                <tr>
                    <td align="center">@option</td>
                </tr>
            }

            for (int i = 7; i < 9; i++)
            {
                int opid = Convert.ToInt32(ids[i]);
                string option = db.Questions_Options.First(a => a.OID == opid).Options.ToString();
                <tr>
                    <td align="center">@option</td>         
                </tr>
            }   
}
        </tbody>
    </table>
    <div id="filters" class="sixteen columns">
        <ul class="clearfix">
            <li>
                <a class="" href="#" data-filter=".branding" onclick="JSFunction1()">
                    <h5>Submit</h5>
                </a>
            </li>
        </ul>
    </div>
</body>
</html>

DevOps_iConfigurator/Views/Shared/_Layout.cshtml
@*<!DOCTYPE HTML>
<html>
<head>
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <!--5grid-->
    <script src="css/5grid/viewport.js"></script><!--[if lt IE 9]><script src="css/5grid/ie.js"></script><![endif]-->
    <link rel="stylesheet" href="css/5grid/core.css" />
    <link rel="stylesheet" href="css/style.css" />
    <!--[if IE 9]><link rel="stylesheet" href="css/style-ie9.css" /><![endif]-->
</head>
<body>
    <!-- ********************************************************* -->
    <div id="header-wrapper">
        <div class="5grid">
            <div class="12u-first">

                <header id="header">
                    <h1><a href="#">put image</a></h1>
                    <nav>
                        <a href="@Url.Action("Index","Home")">Home</a>
                        <a href="@Url.Action("Index","DotNetImage")">.Net</a>
                        <a href="@Url.Action("Index","JavaImage")">Java</a>
                    </nav>
                </header>
            </div>
        </div>
    </div>
    <div id="banner-wrapper">
        <div class="5grid">
            <div class="12u-first">

                <div id="banner">
                    <h2>DevOps iConfigurator</h2>
                    <span>And put something almost as cool here, but a bit longer ...</span>
                </div>
            </div>
        </div>
    </div>  
    <!-- ********************************************************* -->
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>*@